### ISSUE TITLE
[probrem] 出品後に商品編集画面にて画像を全て消すと

### ISSUE THREAD

**Issue by yukitaka0915-se** [freemarket-sample-63a/freemarket_sample_63a#111]
### what

商品の出品時と編集時に画像なしで「出品」ボタンを押すとエラーが発生します。
トップ画面も表示できなくなり、itemsテーブルのレコードを削除しないとエラーが解消
できなくなっています。

### Why

ショッピングサイトアプリとして動作しないので、 
商品を出品、編集する場合は画像を必須入力にしましょう。

**Comment by sggkmrsk** [comment]
すっかり忘れていたのですが、プルリクエスト＃112で修正をかけています。
close承認をお願いします。

**Comment by yukitaka0915-se** [comment]
確認しました。
本件はクローズといたします。
