### ISSUE TITLE
商品出品ボタンを押すとアイテムIDが見つかりませんとエラー表示される

### ISSUE THREAD

**Issue by miura39** [freemarket-sample-63a/freemarket_sample_63a#119]
#バグ内容

http://18.177.209.89/items/new
で出品するとエラーが発生

#実行環境

GoogleChrome

#再現手順

1.写真１枚選択（今回実践したのが１枚）
2.商品名〜販売価格まで必須項目入力
3.出品するを選択

#想定
root pathへのid設定？
Controllerでのid引き渡す処理？

確認してみます。

**Comment by sggkmrsk** [comment]
おそらくカテゴリーの選択が不十分で、エラーになっています。
カテゴリー部分にバリデーション をかけるか（理想）、itemが保存できなかった場合の処置を追加することで回避できると思います（応急処置）
まずは応急処置で対応します。

**Comment by miura39** [comment]
確認してみました。
ひとまず、カテゴリーは全て選択されていてもエラー発生していると思います。
https://gyazo.com/e75574be4a31ce7f00dc750f029c5beb

**Comment by sggkmrsk** [comment]
出品できるケースはありますか？
全項目入力しているとちゃんと出品できているのですが。

**Comment by miura39** [comment]
今のところ出品できないです。
堀さんが出品できたケース教えてください。
画像は jpg png svgで全て試しました。

**Comment by sggkmrsk** [comment]
現時点の想定
・ユーザログインはできてますか？
・画像の容量は大きくないですか？
トップページに戻ってユーザログインしているか確認してもらうのと、画像の容量の確認をお願いします。

**Comment by miura39** [comment]
今一つ出品できました。
またやったらエラーになるので、全て選択していても選択内容によって
エラーが発生しているのかもしれません。

ユーザーログインはできています。
また、写真は３００KB以下のものです。

**Comment by sggkmrsk** [comment]
再現内容を細かく分析する必要あるかもしれませんね。
取り急ぎはItem.saveに失敗した際の記述を追加して回避します。

**Comment by miura39** [comment]
金額上限あります？？
一つわかったのは10,000,000円だと全部エラーになります。

**Comment by sggkmrsk** [comment]
あります
9,999,999上限ですね
バリデーション かけてるので、レコードに登録されません

**Comment by sggkmrsk** [comment]
金額入力欄に入力桁数の制限も掛けた方が良さそう

**Comment by miura39** [comment]
9,999,999を超えると先ほど送ったものと同じエラーがでます。
https://gyazo.com/bedb91825fa960ae4870ca6c3ec3064c

今のところ、堀さんが言っていた全て選択しないパターン。
金額が9,999,999を超えたときのエラーは同じになるようです。

今回は必要ないと思いますが、本来ならこのエラーも想定してつけておくと良いですね。

**Comment by miura39** [comment]
そして、僕は見事に２パターンを交互に繰り返してエラーを発生させていたようです。
全部選択して金額を規定内にすれば登録できています。
欲張りすぎました。。。

**Comment by sggkmrsk** [comment]
するべきことが決まって良かったです
・Item.save失敗時の処理を追加する。
・金額入力部分に桁数制限をかける。

**Comment by sggkmrsk** [comment]
#126のプルリクエストで対応完了したため、クローズ承認お願いします。

**Comment by miura39** [comment]
問題ありません。クローズします。
