### ISSUE TITLE
商品出品ボタンを押すとアドレスが見つからないというエラーになる

### ISSUE THREAD

**Issue by tomoyaueno29** [freemarket-sample-63a/freemarket_sample_63a#121]
### 実行環境
GoogleChrome
### 再現手順
アイテム出品の全ての欄を入力
### エラー内容
アイテム出品するとItemsControllerのset_user_addressメソッドでidが見つからないというエラーになります。

**Comment by tomoyaueno29** [comment]
rails db:seedを実行してもエラーが起きる

**Comment by tomoyaueno29** [comment]
ユーザーが設定の発送元・お届け住所を登録しているとこのエラーは出ませんでしたが、未登録のまま出品をしてしまうと上記のエラーが起こるので、出品ページにとぶ前にcurrent_userがaddressを持っている場合と持っていない場合で条件分岐をする必要があります。

**Comment by sggkmrsk** [comment]
対応完了したためクローズ承認お願いします

**Comment by tomoyaueno29** [comment]
了解しました。
ありがとうございました。
