### ISSUE TITLE
商品出品、商品編集で販売手数料、販売利益が表記されない。

### ISSUE THREAD

**Issue by sggkmrsk** [freemarket-sample-63a/freemarket_sample_63a#124]
今まではコントローラー側で内部計算し、レコードを作成するようにしていたものの、
ユーザビリティを考慮し、Javascript を用いて表示する必要があると思われる。

▪️方針案
JSで価格のchage時にイベントを発生させ、hidden_fieldを作成し、formでコントローラーへ値を引き渡す。

**Comment by yukitaka0915-se** [comment]
編集機能にて、JSで金額を変更したら販売利益(profit_price)が変更出来たのですが、
コントローラーでparamsをみるとprofit_priceが取得できていないですね。何でだろう？

- edit.html.haml
(5行目：編集不可のtextfieldを追加して、profit_priceに紐付け)
[![Screenshot from Gyazo](https://gyazo.com/3557ca5765c6a971aac5e4c3194ad8ac/raw)](https://gyazo.com/3557ca5765c6a971aac5e4c3194ad8ac)

- コントローラーのparams
 (permitの中に **profit_price** がない)
`
[3] pry(#<ItemsController>)> params.require(:item).permit(:brand_id,:category_id,:shippingway_id,:product_size_id,
:condition_num,:daystoship_num,:title,:description,:price,:feerate,:profit_price,
 [item_images_attributes: [:image, :_destroy, :id]])
=> <ActionController::Parameters {"brand_id"=>"", "category_id"=>"19", "shippingway_id"=>"3",
 "product_size_id"=>"2", "condition_num"=>"brand_new", "daystoship_num"=>"one_to_two",
 "title"=>"森林浴ツアーチケット", "description"=>"test",
 "price"=>"8000", "feerate"=>"0.1",
 "item_images_attributes"=><ActionController::Parameters 
{"0"=><ActionController::Parameters 
{"_destroy"=>"0", "id"=>"16"} permitted: true>, "1"=><ActionController::Parameters {"_destroy"=>"0", "id"=>"17"} permitted: true>, "2"=><ActionController::Parameters {"_destroy"=>"0", "id"=>"18"} permitted: true>, "3"=><ActionController::Parameters {"_destroy"=>"0", "id"=>"19"} permitted: true>, "4"=><ActionController::Parameters {"_destroy"=>"0", "id"=>"20"} permitted: true>} permitted: true>} permitted: true>
`

- 編集動作
[![Screenshot from Gyazo](https://gyazo.com/219e3a39e1939365caf3990ffa8ec459/raw)](https://gyazo.com/219e3a39e1939365caf3990ffa8ec459)

**Comment by sggkmrsk** [comment]
jsのコード見たいなあ

**Comment by yukitaka0915-se** [comment]
JSコードは、こんな感じのを最下部に追加しました。

items.js
```

  //ここから価格設定後の金額表示処理
  const NumberWithDelimiter = (number) => {
    return "¥" + String(number).replace(/(\d)(?=(\d\d\d)+(?!\d))/g, '$1,');
  }
  $("#item_price").change(function () {
    let price = parseInt($("#item_price").val().replace(/[^0-9]/g, ''));
    let rate = parseFloat($("#item_feerate").val());
    let prifit_price = "";
    if (Number.isFinite(price) && Number.isFinite(rate)) {
      prifit_price = NumberWithDelimiter(price - (price * rate));
    }
    $("#item_profit_price").val(prifit_price);
  });

```

**Comment by sggkmrsk** [comment]
jsでinput tagまるっと差し替えた方がいい気がします。
検証ツールで見ると、inputのvalueの値の変化がないように見えます。

**Comment by yukitaka0915-se** [comment]
たしかに、現状のJSではinputタグのvalue値は変わってないですね。
hiden_fieldで渡す方法を試してから、JSでhtmlをbuildする方法をやってみます。

**Comment by sggkmrsk** [comment]
お、なんか初めて聞く手法ですね、楽しみに待ってます

**Comment by yukitaka0915-se** [comment]
なんとか形になったのでプルリク出します。

**Comment by yukitaka0915-se** [comment]
プルリク#130にて対応しました。
クローズ承認をお願いします。

**Comment by sggkmrsk** [comment]
確認しました。
本件クローズします。
