### ISSUE TITLE
１枚のみ画像がある商品で画像を追加後に既存の画像を削除して編集した際に商品登録できない

### ISSUE THREAD

**Issue by sggkmrsk** [freemarket-sample-63a/freemarket_sample_63a#129]
以下の手順で編集不能となる

▪️想定するエラーとなる原因
下記記述内の以下部分が起因していると想定
    if params[:item]['item_images_attributes']['0']['_destroy'] == "1"

```items_controller.rb
  def update
    item = Item.find(params[:id])
    if params[:item]['item_images_attributes']['0']['_destroy'] == "1"
      redirect_to edit_item_path(item.id), notice:"画像がない商品は登録できません。"
    else
      item.update(item_update_params)
      redirect_to item_path(item.id)
    end
  end
```

**Comment by miura39** [comment]
if params[:item]['item_images_attributes']['0']['_destroy'] == "1"
      redirect_to edit_item_path(item.id), notice:"画像がない商品は登録できません。"
    

この部分をコメントアウトにすれば、
「１枚のみ画像がある商品で画像を追加後に既存の画像を削除して編集した際に商品登録できない」
は解消していますね。

確かに上記のソースの編集を行い、画像がない時のエラーを回避すればクリア出来そうです。

**Comment by sggkmrsk** [comment]
pull request#132で改修したため、クローズします。
